### ISSUE TITLE
Feature: 对子机构和通讯作者的其他数据源支持

### ISSUE THREAD

**Issue by nkh0472** [doublessay/histcite-python#12]
### Feature类型

- [ ] 参考文献解析
- [ ] 支持其他数据源
- [x] 增加其他功能

### 使用数据源

Web of Science

### Feature描述

相关实现见#8

已经实现了对子机构和通讯作者的统计，但因为我只使用WOS，因此没有兴趣支持其他格式。

**Comment by doublessay** [comment]
[v1.1.0](https://pypi.org/project/histcite-python/1.1.0/) has support the feature.
