### ISSUE TITLE
Feature: 解析通讯作者的通讯邮箱

### ISSUE THREAD

**Issue by nkh0472** [doublessay/histcite-python#13]
### Feature类型

- [ ] 参考文献解析
- [ ] 支持其他数据源
- [X] 增加其他功能

### 使用数据源

Web of Science

### Feature描述

该功能依赖 #8 中新增的CAU列，及额外导入的EM列。

我已经在
https://github.com/nkh0472/histcite-python/blob/d74d9d59fb5d9590c901faf4ae4e3b03c3b72175/histcite/process_email.py
中提供了完整的实现，但是没有嵌入到包的类里面。

函数会返回一个包含了所有通讯作者及其邮箱的字典，对于没有办法找到准确一一对应邮箱的数据保存在df['CAU_u']和df['EM_u']中。

对我个人已经够用，没有继续改进的必要了……

如果作者有兴趣可以把这个植入到项目里，不然就关掉issue吧。

**Comment by doublessay** [comment]
😊
