### ISSUE TITLE
对象合并错误

### ISSUE THREAD

**Issue by APE-147** [doublessay/histcite-python#2]
在使用 demo.ipynb 的过程中
运行
"
process = ProcessFile(docs_df, source_type)
refs_df = process.extract_reference()  # 提取参考文献
citation_relationship = process.process_citation(refs_df)  # 识别引用关系
"
出现以下错误
"
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[/Users/ns/Library/CloudStorage/Dropbox/-Code-/Env/V-Jupyter/Function/histcite-python](https://file+.vscode-resource.vscode-cdn.net/Users/ns/Library/CloudStorage/Dropbox/-Code-/Env/V-Jupyter/Function/histcite-python) demo.ipynb Cell 6 line 3
      [1](vscode-notebook-cell:/Users/ns/Library/CloudStorage/Dropbox/-Code-/Env/V-Jupyter/Function/histcite-python%20demo.ipynb#W5sZmlsZQ%3D%3D?line=0) process = ProcessFile(docs_df, source_type)
      [2](vscode-notebook-cell:/Users/ns/Library/CloudStorage/Dropbox/-Code-/Env/V-Jupyter/Function/histcite-python%20demo.ipynb#W5sZmlsZQ%3D%3D?line=1) refs_df = process.extract_reference()  # 提取参考文献
----> [3](vscode-notebook-cell:/Users/ns/Library/CloudStorage/Dropbox/-Code-/Env/V-Jupyter/Function/histcite-python%20demo.ipynb#W5sZmlsZQ%3D%3D?line=2) citation_relationship = process.process_citation(refs_df)

File [~/anaconda3/envs/Python-39/lib/python3.9/site-packages/histcite/process_file.py:83](https://file+.vscode-resource.vscode-cdn.net/Users/ns/Library/CloudStorage/Dropbox/-Code-/Env/V-Jupyter/Function/~/anaconda3/envs/Python-39/lib/python3.9/site-packages/histcite/process_file.py:83), in ProcessFile.process_citation(self, refs_df)
     81     self._docs_df["DI"] = self._docs_df["DI"].str.lower()
     82     refs_df = refs_df.astype({"PY": "int64[pyarrow]"})
---> 83     cited_doc_index_series = RecognizeReference.recognize_wos_reference(
     84         self._docs_df, refs_df
     85     )
     87 elif self._source == "cssci":
     88     self._docs_df["TI"] = self._docs_df["TI"].str.lower()

File [~/anaconda3/envs/Python-39/lib/python3.9/site-packages/histcite/recognize_reference.py:86](https://file+.vscode-resource.vscode-cdn.net/Users/ns/Library/CloudStorage/Dropbox/-Code-/Env/V-Jupyter/Function/~/anaconda3/envs/Python-39/lib/python3.9/site-packages/histcite/recognize_reference.py:86), in RecognizeReference.recognize_wos_reference(docs_df, refs_df)
     84 # DOI not exists
     85 compare_cols = ["FAU", "PY", "J9", "BP"]
---> 86 result = RecognizeReference.recognize_refs_factory(
     87     docs_df[docs_df["DI"].isna()], refs_df[refs_df["DI"].isna()], compare_cols
     88 )
     89 cited_refs_series = result_doi.combine(result, _merge_lists)
     90 # local_refs_series = pd.concat([result_doi[1], result[1]])

File [~/anaconda3/envs/Python-39/lib/python3.9/site-packages/histcite/recognize_reference.py:39](https://file+.vscode-resource.vscode-cdn.net/Users/ns/Library/CloudStorage/Dropbox/-Code-/Env/V-Jupyter/Function/~/anaconda3/envs/Python-39/lib/python3.9/site-packages/histcite/recognize_reference.py:39), in RecognizeReference.recognize_refs_factory(docs_df, refs_df, compare_cols, drop_duplicates)
     37 docs_df = docs_df[["doc_index"] + compare_cols]
     38 refs_df = refs_df[["doc_index", "ref_index"] + compare_cols]
---> 39 shared_df = pd.merge(
     40     refs_df, docs_df, how="left", on=compare_cols, suffixes=("_x", "_y")
     41 ).dropna(subset="doc_index_y")
     42 shared_df = shared_df.astype({"doc_index_y": "int64"})
     43 cited_refs_series = shared_df.groupby("doc_index_x")["doc_index_y"].apply(list)

File [~/anaconda3/envs/Python-39/lib/python3.9/site-packages/pandas/core/reshape/merge.py:144](https://file+.vscode-resource.vscode-cdn.net/Users/ns/Library/CloudStorage/Dropbox/-Code-/Env/V-Jupyter/Function/~/anaconda3/envs/Python-39/lib/python3.9/site-packages/pandas/core/reshape/merge.py:144), in merge(left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
    127 @Substitution("\nleft : DataFrame or named Series")
    128 @Appender(_merge_doc, indents=0)
    129 def merge(
   (...)
    142     validate: str | None = None,
    143 ) -> DataFrame:
--> 144     op = _MergeOperation(
    145         left,
    146         right,
    147         how=how,
    148         on=on,
    149         left_on=left_on,
    150         right_on=right_on,
    151         left_index=left_index,
    152         right_index=right_index,
    153         sort=sort,
    154         suffixes=suffixes,
    155         indicator=indicator,
    156         validate=validate,
    157     )
    158     return op.get_result(copy=copy)

File [~/anaconda3/envs/Python-39/lib/python3.9/site-packages/pandas/core/reshape/merge.py:737](https://file+.vscode-resource.vscode-cdn.net/Users/ns/Library/CloudStorage/Dropbox/-Code-/Env/V-Jupyter/Function/~/anaconda3/envs/Python-39/lib/python3.9/site-packages/pandas/core/reshape/merge.py:737), in _MergeOperation.__init__(self, left, right, how, on, left_on, right_on, axis, left_index, right_index, sort, suffixes, indicator, validate)
    729 (
    730     self.left_join_keys,
    731     self.right_join_keys,
    732     self.join_names,
    733 ) = self._get_merge_keys()
    735 # validate the merge keys dtypes. We may need to coerce
    736 # to avoid incompatible dtypes
--> 737 self._maybe_coerce_merge_keys()
    739 # If argument passed to validate,
    740 # check if columns specified as unique
    741 # are in fact unique.
    742 if validate is not None:

File [~/anaconda3/envs/Python-39/lib/python3.9/site-packages/pandas/core/reshape/merge.py:1389](https://file+.vscode-resource.vscode-cdn.net/Users/ns/Library/CloudStorage/Dropbox/-Code-/Env/V-Jupyter/Function/~/anaconda3/envs/Python-39/lib/python3.9/site-packages/pandas/core/reshape/merge.py:1389), in _MergeOperation._maybe_coerce_merge_keys(self)
   1383     # unless we are merging non-string-like with string-like
   1384     elif (
   1385         inferred_left in string_types and inferred_right not in string_types
   1386     ) or (
   1387         inferred_right in string_types and inferred_left not in string_types
   1388     ):
-> 1389         raise ValueError(msg)
   1391 # datetimelikes must match exactly
   1392 elif needs_i8_conversion(lk.dtype) and not needs_i8_conversion(rk.dtype):

ValueError: You are trying to merge on object and int64[pyarrow] columns. If you wish to proceed you should use pd.concat
"

**Comment by doublessay** [comment]
请问你使用的pandas和histcite-python版本号分别是什么？

目前histcite-python的最新版应该是[0.5.5](https://pypi.org/project/histcite-python/0.5.5/)，如果不是最新版本的话请先升级 `pip install -U histcite-python`

我目前使用2.1.1版本的pandas和0.5.5版本的histcite-python，在wos数据集上测试没出现bug。我也检查了一下出问题的代码部分，暂时没排查出什么错误。

**Comment by APE-147** [comment]
> 请问你使用的pandas和histcite-python版本号分别是什么？
> 
> 目前histcite-python的最新版应该是[0.5.5](https://pypi.org/project/histcite-python/0.5.5/)，如果不是最新版本的话请先升级 `pip install -U histcite-python`
> 
> 我目前使用2.1.1版本的pandas和0.5.5版本的histcite-python，在wos数据集上测试没出现bug。我也检查了一下出问题的代码部分，暂时没排查出什么错误。

好的👌🏻, 在更新pandas之后问题解决, 十分感谢
